version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies... (none for static site)"
  build:
    commands:
      - echo "Build phase: Nothing to compile"
  post_build:
    commands:
      - echo "Post-build: Preparing for deployment"

artifacts:
  files:
    - index.html
    - styles.css
